services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: queue-room
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_DB=3
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=123456
      - WEB_URL=https://www.google.com
    depends_on:
      - redis
    networks:
      - app-network

  scheduler:
    container_name: scheduler
    build:
      dockerfile: docker/Dockerfile
      context: queue-room-scheduler
    environment:
      - NODE_ENV=development
      - REDIS_DB=3
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:7-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - app-network

volumes:
  redis-data:

networks:
  app-network:
    driver: bridge
